x-spring-common: &spring-common
  SPRING_PROFILES_ACTIVE: docker
  SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888

x-spring-healthcheck: &spring-healthcheck
  interval: 10s
  timeout: 5s
  retries: 10
  start_period: 30s

x-spring-service: &spring-service
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "5"

services:

  postgres:
    image: postgres:17
    container_name: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: userService

    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - micro-commerce-network

  #  --------------------------
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 10

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    networks:
      - micro-commerce-network

  #  --------------------------
  redis:
    image: redis:8
    container_name: redis

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - micro-commerce-network

  #  --------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.2
    container_name: elasticsearch-com

    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"

    ports:
      - "9200:9200"
      - "9300:9300"

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 20

    networks:
      - micro-commerce-network


  #  --------------------------
  config-server:
    <<: *spring-service

    image: fardeenhsiddiqui/config-server:latest
    container_name: config-server

    ports:
      - "8888:8888"

    healthcheck:
      <<: *spring-healthcheck
      test:
        - CMD
        - wget
        - --spider
        - -q
        - http://localhost:8888/actuator/health

    environment:
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}

    networks:
      - micro-commerce-network

  #  --------------------------
  discovery-server:
    <<: *spring-service

    image: fardeenhsiddiqui/discovery-server:latest
    container_name: discovery-server

    ports:
      - "8761:8761"

    healthcheck:
      <<: *spring-healthcheck
      test:
        - CMD
        - wget
        - --spider
        - -q
        - http://localhost:8761/actuator/health

    environment:
      <<: *spring-common

    depends_on:
      config-server:
        condition: service_healthy

    networks:
      - micro-commerce-network

  #  --------------------------
  user-service:
    <<: *spring-service

    image: fardeenhsiddiqui/user-service:latest
    container_name: user-service

    ports:
      - "8081:8081"

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

    environment:
      <<: *spring-common

    healthcheck:
      <<: *spring-healthcheck
      test:
        - CMD
        - wget
        - --spider
        - -q
        - http://localhost:8081/actuator/health

    networks:
      - micro-commerce-network

  #  --------------------------
  product-service:
    <<: *spring-service

    image: fardeenhsiddiqui/product-service:latest
    container_name: product-service

    ports:
      - "8082:8082"

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

    environment:
      <<: *spring-common

    healthcheck:
      <<: *spring-healthcheck
      test:
        - CMD
        - wget
        - --spider
        - -q
        - http://localhost:8082/actuator/health

    networks:
      - micro-commerce-network

  #  --------------------------
  api-gateway:
    <<: *spring-service

    image: fardeenhsiddiqui/api-gateway:latest
    container_name: api-gateway

    ports:
      - "8080:8080"

    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

    environment:
      <<: *spring-common

    healthcheck:
      <<: *spring-healthcheck
      test:
        - CMD
        - wget
        - --spider
        - -q
        - http://localhost:8080/actuator/health

    networks:
      - micro-commerce-network

  #  --------------------------
  notification-service:
    <<: *spring-service

    image: fardeenhsiddiqui/notification-service:latest
    container_name: notification-service

    ports:
      - "8083:8083"

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

    environment:
      <<: *spring-common
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

    healthcheck:
      <<: *spring-healthcheck
      test:
        - CMD
        - wget
        - --spider
        - -q
        - http://localhost:8083/actuator/health

    networks:
      - micro-commerce-network



volumes:
  postgres-data:
  rabbitmq-data:
  redis-data:
  elasticsearch-data:

networks:
  micro-commerce-network:
    driver: bridge