x-spring-common: &spring-common
  SPRING_PROFILES_ACTIVE: docker
  SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888

services:

  postgres:
    image: postgres:17
    container_name: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: userService

    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - micro-commerce-network

  #  --------------------------
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 10

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    networks:
      - micro-commerce-network

  #  --------------------------
  redis:
    image: redis:8
    container_name: redis

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - micro-commerce-network

  #  --------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.2
    container_name: elasticsearch-com

    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"

    ports:
      - "9200:9200"
      - "9300:9300"

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 20

    networks:
      - micro-commerce-network


  #  --------------------------
  config-server:
    image: config-server
    container_name: config-server

    ports:
      - "8888:8888"

    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    environment:
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}

    networks:
      - micro-commerce-network

  #  --------------------------
  discovery-server:
    image: discovery-server
    container_name: discovery-server

    ports:
      - "8761:8761"

    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    environment:
      <<: *spring-common

    depends_on:
      config-server:
        condition: service_healthy

    networks:
      - micro-commerce-network

  #  --------------------------
  user-service:
    image: user-service
    container_name: user-service

    ports:
      - "8081:8081"

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

    environment:
      <<: *spring-common

    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - micro-commerce-network

  #  --------------------------
  product-service:
    image: product-service
    container_name: product-service

    ports:
      - "8082:8082"

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

    environment:
      <<: *spring-common

    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - micro-commerce-network

  #  --------------------------
  api-gateway:
    image: api-gateway
    container_name: api-gateway

    ports:
      - "8080:8080"

    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

    environment:
      <<: *spring-common

    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - micro-commerce-network

  #  --------------------------
  notification-service:
    image: notification-service
    container_name: notification-service

    ports:
      - "8083:8083"

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

    environment:
      <<: *spring-common
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - micro-commerce-network



volumes:
  postgres-data:
  rabbitmq-data:
  redis-data:
  elasticsearch-data:

networks:
  micro-commerce-network:
    driver: bridge