# Postgres SQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/notificationService
spring.datasource.username= postgres
spring.datasource.password= root
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081
# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.name=notificationService

# Core SMTP Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Security Protocols
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Connection Timeouts (Prevents thread blocking)
#spring.mail.properties[mail.smtp.connectiontimeout]=5000
#spring.mail.properties[mail.smtp.timeout]=3000
#spring.mail.properties[mail.smtp.writetimeout]=5000

# Rabbit MQ Config
# Run Rabbit MQ Command : docker run --rm -it -p 15672:15672 -p 5672:5672 rabbitmq:4.1.0-management
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
logging.level.org.springframework.amqp=DEBUG
#logging.level.org.springframework.security=DEBUG
#rabbitmq.enabled=true
# or
#spring.rabbitmq.listener.simple.auto-startup=true
#spring.rabbitmq.listener.direct.auto-startup=true

