# Postgres SQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/notificationService
spring.datasource.username= postgres
spring.datasource.password= root
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081
# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.name=notificationService

# Core SMTP Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fardeenhsiddiqui98@gmail.com


# Security Protocols
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Connection Timeouts (Prevents thread blocking)
#spring.mail.properties[mail.smtp.connectiontimeout]=5000
#spring.mail.properties[mail.smtp.timeout]=3000
#spring.mail.properties[mail.smtp.writetimeout]=5000

